PersonalWebsite/Areas/Admin/Controllers/AboutMeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PersonalWebsite.Data;
using PersonalWebsite.Models;
using PersonalWebsite.Services;

namespace PersonalWebsite.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class AboutMeController : Controller
    {
        private readonly AppDbContext _db;

        private readonly IPictureService _pictureService;

        public AboutMeController(AppDbContext db, IPictureService pictureService)
        {
            _db = db;
            _pictureService = pictureService;
        }

        [Route("[controller]")]
        public async Task<IActionResult> Index()
        {
            var aboutMe = await _db.AboutMe
                .Include(a => a.Technologies)
                .FirstOrDefaultAsync(a => a.Id.Equals(1));
            return View(aboutMe);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("[controller]/[action]")]
        public async Task<IActionResult> Edit(AboutMe aboutMe, IFormFile imageFile)
        {
            if (!ModelState.IsValid)
            {
                return View("Index", aboutMe);
            }

            if (imageFile != null)
            {
                var newImageName = await _pictureService.EditAboutMeImageAsync(imageFile, aboutMe.Image);

                if (string.IsNullOrEmpty(newImageName))
                {
                    TempData["Error"] = "حجم عکس بیش از 500 کیلوبایت می باشد";
                    return RedirectToAction("Index");
                }

                aboutMe.Image = newImageName;
            }

            _db.AboutMe.Update(aboutMe);
            await _db.SaveChangesAsync();

            TempData["Success"] = "اطلاعات با موفقیت ذخیره شد";
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("[controller]/[action]")]
        public async Task<IActionResult> AddSkill(string skillName)
        {
            if (string.IsNullOrEmpty(skillName))
            {
                TempData["Error"] = "عنوان مهارت نامعتبر است";
                return RedirectToAction("Index");
            }

            if (await _db.Technologies.CountAsync() > 30)
            {
                TempData["Error"] = "تعداد مهارت ها به حداکثر حد مجاز رسیده است";
                return RedirectToAction("Index");
            }

            var technology = new Technology()
            {
                AboutMeId = 1,
                Title = skillName
            };

            await _db.Technologies.AddAsync(technology);
            await _db.SaveChangesAsync();

            TempData["Success"] = "مهارت با موفقیت افزوده شد";
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("[controller]/[action]")]
        public async Task<IActionResult> EditSkill(string skillName, int id = 0)
        {
            if (id == 0 || string.IsNullOrEmpty(skillName))
            {
                TempData["Error"] = "عنوان مهارت نامعتبر است";
                return RedirectToAction("Index");
            }

            var technology = await _db.Technologies.FindAsync(id);

            if (technology is null)
            {
                TempData["Error"] = "لطفا از دستکاری داده ها اجتناب کنید";
                return RedirectToAction("Index");
            }

            technology.Title = skillName;

            _db.Technologies.Update(technology);
            await _db.SaveChangesAsync();

            TempData["Success"] = "مهارت با موفقیت ویرایش شد";
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("[controller]/[action]")]
        public async Task<IActionResult> DeleteSkill(int id = 0)
        {
            if (id is 0)
            {
                return StatusCode(404);
            }

            var skill = await _db.Technologies.FindAsync(id);

            if (skill is null)
            {
                return StatusCode(404);
            }

            _db.Technologies.Remove(skill);
            await _db.SaveChangesAsync();

            return StatusCode(200);
        }
    }
}

PersonalWebsite/Areas/Admin/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PersonalWebsite.Data;

namespace PersonalWebsite.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class MessageController : Controller
    {
        private readonly AppDbContext _db;

        public MessageController(AppDbContext db)
        {
            _db = db;
        }

        [Route("Messages")]
        public async Task<IActionResult> Index()
        {
            var messages = await _db.ContactForms.ToListAsync();
            return View(messages);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id = 0)
        {
            if (id is 0)
            {
                return NotFound();
            }

            var message = await _db.ContactForms.FindAsync(id);

            if (message is null)
            {
                return NotFound();
            }

            _db.ContactForms.Remove(message);
            await _db.SaveChangesAsync();

            TempData["Success"] = "بازخورد با موفقیت حذف شد";
            return RedirectToAction("Index");
        }

    }
}

PersonalWebsite/Areas/Admin/Controllers/SkillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PersonalWebsite.Areas.Admin.DTOs;
using PersonalWebsite.Data;
using PersonalWebsite.Models;
using PersonalWebsite.Utilities;

namespace PersonalWebsite.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class SkillsController : Controller
    {
        private readonly AppDbContext _db;

        public SkillsController(AppDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            var skillViewModel = new SkillViewModel
            {
                TechnicalSkills = await _db.TechnicalSkills.ToListAsync(),
                PersonalSkills = await _db.PersonalSkills.ToListAsync()
            };
            return View(skillViewModel);
        }

        #region Personal Skill

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("[controller]/[action]")]
        public async Task<IActionResult> EditPersonalSkills(List<PersonalSkill> personalSkills)
        {
            _db.PersonalSkills.UpdateRange(personalSkills);
            await _db.SaveChangesAsync();

            TempData["Success"] = "اطلاعات با موفقیت بروزرسانی شد";
            return RedirectToAction("Index");
        }

        #endregion

        #region Technical Skill

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("[controller]/[action]")]
        public async Task<IActionResult> AddTechnicalSkill(string technicalSkillName, int technicalSkillProgress = 0)
        {
            if (string.IsNullOrEmpty(technicalSkillName))
            {
                TempData["Error"] = "لطفا داده های مورد نیاز را وارد کنید";
                return RedirectToAction("Index");
            }

            var technicalSkill = new TechnicalSkill
            {
                Progress = technicalSkillProgress,
                Title = technicalSkillName
            };

            await _db.TechnicalSkills.AddAsync(technicalSkill);
            await _db.SaveChangesAsync();

            TempData["Success"] = "مهارت با موفقیت اضافه شد";
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("[controller]/[action]")]
        public async Task<IActionResult> EditTechnicalSkills(List<TechnicalSkill> technicalSkills)
        {
            _db.TechnicalSkills.UpdateRange(technicalSkills);
            await _db.SaveChangesAsync();

            TempData["Success"] = "اطلاعات با موفقیت بروزرسانی شد";
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Route("[controller]/[action]")]
        public async Task<IActionResult> DeleteTechnicalSkills([ModelBinder(typeof(SkillRemoveModelBinder))] List<int> ids)
        {
            var skills = new List<TechnicalSkill>();
            foreach (var id in ids)
            {
                skills.Add(await _db.TechnicalSkills.FindAsync(id));
            }
            _db.TechnicalSkills.RemoveRange(skills);
            await _db.SaveChangesAsync();

            TempData["Success"] = "اطلاعات با موفقیت بروزرسانی شد";
            return RedirectToAction("Index");
        }

        #endregion
    }
}

PersonalWebsite/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PersonalWebsite.Data;
using PersonalWebsite.Models.Weblog;
using PersonalWebsite.Utilities;

namespace PersonalWebsite.Controllers
{
    public class BlogController : Controller
    {
        private readonly AppDbContext _db;

        public BlogController(AppDbContext db)
        {
            _db = db;
        }

        //All Archives
        [Route("[controller]/Archive")]
        public async Task<IActionResult> Index(string searchString, string currentFilter, int? page)
        {
            if (searchString != null)
            {
                page = 1;
                searchString = searchString.EncodeUrl();
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            const int pageSize = 6;
            var pageNumber = (page ?? 1);

            if (string.IsNullOrEmpty(searchString))
            {
                var blogs = _db.Blogs.OrderByDescending(a => a.DateTime);
                return View(await PaginatedList<Blog>.CreateAsync(blogs.AsNoTracking(), pageNumber, pageSize));
            }

            var searchResult = _db.Blogs
                .Include(a => a.Category)
                .Where(a =>
                    a.Tags.Contains(searchString.EncodeUrl()) || a.Description.Contains(searchString.EncodeUrl()) ||
                    a.Title.Contains(searchString.EncodeUrl()) ||
                    a.ShortDescription.Contains(searchString.EncodeUrl()) ||
                    a.Category.Name.Equals(searchString.EncodeUrl()))
                .Distinct()
                .OrderByDescending(a => a.DateTime);

            return View(await PaginatedList<Blog>.CreateAsync(searchResult, pageNumber, pageSize));
        }

        [Route("[controller]/{id}/{title}")]
        public async Task<IActionResult> GetBlog(int id, string title)
        {
            var blog = await _db.Blogs.FindAsync(id);

            if (blog == null)
            {
                return NotFound();
            }

            blog.ViewCount++;
            _db.Update(blog);
            await _db.SaveChangesAsync();

            return View(blog);
        }
    }
}

PersonalWebsite/Areas/Admin/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>

<html lang="en" dir="rtl">
<head>
    <partial name="_AdminMetaTags" />

    <!-- App Favicon -->
    <link rel="shortcut icon" href="/logo.png">

    <!-- App title -->
    <title>@ViewData["Title"]</title>

    <!-- App CSS -->
    <link href="/Admin/css/bootstrap-rtl.min.css" rel="stylesheet" type="text/css" />
    <link href="/Admin/css/core.css" rel="stylesheet" type="text/css" />
    <link href="/Admin/css/components.css" rel="stylesheet" type="text/css" />
    <link href="/Admin/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="/Admin/css/pages.css" rel="stylesheet" type="text/css" />
    <link href="/Admin/css/menu.css" rel="stylesheet" type="text/css" />
    <link href="/Admin/css/responsive.css" rel="stylesheet" type="text/css" />
    <link href="/Admin/css/custom-style.css" rel="stylesheet">

    <!-- Toaster -->
    <link rel="stylesheet" href="/Admin/plugins/toastr/toastr.min.css">

    <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="/Admin/js/modernizr.min.js"></script>
</head>
<body>
    <div class="account-pages"></div>
    <div class="clearfix"></div>
    <div class="wrapper-page">
        <div class="text-center">
            <a class="logo"><span>پنل <span>مدیریت محتوا</span></span></a>
            <h5 class="text-muted m-t-0 font-600">وبسایت شخصی مسعود خدادادی</h5>
        </div>
        @RenderBody()
        <!-- end card-box-->
    </div>
    <!-- end wrapper page -->
    <script>
        var resizefunc = [];
    </script>

    <!-- jQuery  -->
    <script src="/Admin/js/jquery.min.js"></script>
    <script src="/Admin/js/bootstrap-rtl.min.js"></script>
    <script src="/Admin/js/detect.js"></script>
    <script src="/Admin/js/fastclick.js"></script>
    <script src="/Admin/js/jquery.slimscroll.js"></script>
    <script src="/Admin/js/jquery.blockUI.js"></script>
    <script src="/Admin/js/waves.js"></script>
    <script src="/Admin/js/wow.min.js"></script>
    <script src="/Admin/js/jquery.nicescroll.js"></script>
    <script src="/Admin/js/jquery.scrollTo.min.js"></script>

    <!-- App js -->
    <script src="/Admin/js/jquery.core.js"></script>
    <script src="/Admin/js/jquery.app.js"></script>

    <partial name="_Toaster" />

    @await Html.PartialAsync("_ValidationScriptsPartial")
</body>
</html>

PersonalWebsite/Areas/Admin/Views/Shared/_AdminMetaTags.cshtml
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="صفحه مدیریت محتوای مهندس مسعود خدادادی" />
<meta name="keywords" content="creative, cv, developer,  online cv, online resume, powerful portfolio, professional, professional resume, responsive, resume, vcard " />
<meta name="developer" content="Masoud Khodadadi">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!--instagram-->
<meta property="og:title" content="صفحه مدیریت محتوای مهندس مسعود خدادادی">
<meta property="og:image" content="@($"{Context.Request.Scheme}://{Context.Request.Host}/images/profile.jpg")">
<meta property="og:description" content="مدیریت محتوای سایت شخصی مسعود خدادادی">
<meta property="og:url" content="@($"{Context.Request.Scheme}://{Context.Request.Host}{Context.Request.Path}{Context.Request.QueryString}")">

PersonalWebsite/Areas/Admin/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <partial name="_AdminMetaTags" />

    <!-- App Favicon -->
    <link rel="shortcut icon" href="/logo.png">

    <!-- App title -->
    <title>@ViewData["Title"]</title>

    <!-- App CSS -->
    <link href="/Admin/css/bootstrap-rtl.min.css" rel="stylesheet" type="text/css" />
    <link href="/Admin/css/core.css" rel="stylesheet" type="text/css" />
    <link href="/Admin/css/components.css" rel="stylesheet" type="text/css" />
    <link href="/Admin/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="/Admin/css/pages.css" rel="stylesheet" type="text/css" />
    <link href="/Admin/css/menu.css" rel="stylesheet" type="text/css" />
    <link href="/Admin/css/responsive.css" rel="stylesheet" type="text/css" />
    <link href="/Admin/css/custom-style.css" rel="stylesheet">
    <link href="/Admin/plugins/toastr/toastr.min.css" rel="stylesheet" type="text/css" />
    <link href="/Admin/css/AdminLTE.css" rel="stylesheet" type="text/css" />

    <!-- Plugins css-->
    <link href="/Admin/plugins/bootstrap-tagsinput/dist/bootstrap-tagsinput.css" rel="stylesheet" />
    <link href="/css/custom-style.css" rel="stylesheet" />
    <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="/Admin/js/modernizr.min.js"></script>
    <!-- jQuery  -->
    <script src="/Admin/js/jquery.min.js"></script>
    @await RenderSectionAsync("Head", false)
</head>


<body class="fixed-left">
    <!-- Begin page -->
    <div id="wrapper">

        <!-- Top Bar Start -->
        <div class="topbar">

            <!-- LOGO -->
            <div class="topbar-left">
                <a href="" class="logo"><span>پنل <span>ادمین</span></span><i class="zmdi zmdi-layers"></i></a>
            </div>

            <!-- Button mobile view to collapse sidebar menu -->
            <div class="navbar navbar-default" role="navigation">
                <div class="container">

                    <!-- Page title -->
                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <button class="button-menu-mobile open-left">
                                <i class="zmdi zmdi-menu"></i>
                            </button>
                        </li>
                        <li>
                            <h4 class="page-title">@ViewData["Title"]</h4>
                        </li>
                    </ul>

                    <!-- Right(Notification) -->
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <!-- Notification -->
                            <div class="notification-box">
                                <ul class="list-inline m-b-0">
                                    <li>
                                        <a href="javascript:void(0);" class="right-bar-toggle">
                                            <i class="zmdi zmdi-notifications-none"></i>
                                        </a>
                                        <div class="noti-dot">
                                            <span class="dot"></span>
                                            <span class="pulse"></span>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <!-- End Notification bar -->
                            @await RenderSectionAsync("Search", false)
                        </li>
                    </ul>

                </div><!-- end container -->
            </div><!-- end navbar -->
        </div>
        <!-- Top Bar End -->
        <!-- ========== Sidebar Start ========== -->
        <partial name="_Sidebar" />
        <!-- Sidebar End -->
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="content-page">
            <!-- Start content -->
            <div class="content">

                @RenderBody()

                <footer class="footer">
                    Developed By Masoud Khodadadi
                </footer>

            </div>
            <!-- End content-page -->
            <!-- ============================================================== -->
            <!-- End Right content here -->
            <!-- ============================================================== -->
            <!-- Right Sidebar -->
            <partial name="_Notification" />
            <!-- /Right-bar -->

        </div>
        <!-- END wrapper -->

        <script>
            var resizefunc = [];
        </script>

        <!-- jQuery  -->
        <script src="/Admin/js/jquery.min.js"></script>
        <script src="/Admin/js/bootstrap-rtl.min.js"></script>
        <script src="/Admin/js/detect.js"></script>
        <script src="/Admin/js/fastclick.js"></script>
        <script src="/Admin/js/jquery.slimscroll.js"></script>
        <script src="/Admin/js/jquery.blockUI.js"></script>
        <script src="/Admin/js/waves.js"></script>
        <script src="/Admin/js/jquery.nicescroll.js"></script>
        <script src="/Admin/js/jquery.scrollTo.min.js"></script>

        <!-- Bootstrap tags input -->
        <script src="/Admin/plugins/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js"></script>

        <!-- jQuery Validate -->
        <script src="/lib/jquery-validate/jquery.validate.min.js"></script>
        <script src="/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

        @await RenderSectionAsync("Scripts", false)

        <!-- App js -->
        <script src="/Admin/js/jquery.core.js"></script>
        <script src="/Admin/js/jquery.app.js"></script>

        <partial name="_Toaster" />
    </div>
</body>
</html>

PersonalWebsite/Areas/Admin/Views/Shared/_Notification.cshtml
@inject AppDbContext Db

<div class="side-bar right-bar">
    <a href="javascript:void(0);" class="right-bar-toggle">
        <i class="zmdi zmdi-close-circle-o"></i>
    </a>
    <h4 class="">اعلانات</h4>
    <div class="notification-list nicescroll">
        <ul class="list-group list-no-border user-list">
            @{
                if (Db.ContactForms.Any())
                {
                    foreach (var item in Db.ContactForms)
                    {
                        <li class="list-group-item">
                            <a asp-area="Admin" asp-controller="Message" asp-action="Index" class="user-list-item">
                                <div class="icon bg-pink">
                                    <i class="zmdi zmdi-comment"></i>
                                </div>
                                <div class="user-desc">
                                    <span class="name">پیام جدید</span>
                                    <span class="desc">بازخوردی از @item.FirstName @item.LastName</span>
                                    <span class="time">@item.DateTime.ElapsedTimeNotification()</span>
                                </div>
                            </a>
                        </li>
                    }
                }
                else
                {
                    <div class="text-center">
                        هیچ اعلانی وجود ندارد
                    </div>
                }
            }


        </ul>
    </div>
</div>

PersonalWebsite/Areas/Admin/Views/Shared/_Sidebar.cshtml
<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">

        <!-- User -->
        <div class="user-box">
            <div class="user-img">
                <img src="/images/profile.jpg" alt="user-img" title="Mat Helme" class="img-circle img-thumbnail img-responsive">
                <div class="user-status online"><i class="zmdi zmdi-dot-circle"></i></div>
            </div>
            <h5><a href="#">مسعود خدادادی</a> </h5>
            <ul class="list-inline">
                <li>
                    <a asp-area="Admin" asp-controller="Account" asp-action="EditProfile">
                        <i class="zmdi zmdi-settings"></i>
                    </a>
                </li>

                <li>
                    <a asp-area="Admin" asp-controller="Account" asp-action="Logout" class="text-custom">
                        <i class="zmdi zmdi-power"></i>
                    </a>
                </li>
            </ul>
        </div>
        <!-- End User -->
        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <ul>
                <li class="text-muted menu-title">دسته بندی ها</li>

                <li>
                    <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="waves-effect"><i class="zmdi zmdi-view-dashboard"></i> <span> داشبورد </span> </a>
                </li>

                <li>
                    <a asp-area="Admin" asp-controller="Blog" asp-action="AddBlog" class="waves-effect"><i class="fa fa-pencil"></i> <span> افزودن بلاگ </span> </a>
                </li>

                <li>
                    <a asp-area="Admin" asp-controller="Blog" asp-action="Index" class="waves-effect"><i class="fa fa-archive"></i> <span> مدیریت بلاگ ها </span> </a>
                </li>
                
                <li>
                    <a asp-area="Admin" asp-controller="BlogCategory" asp-action="Index" class="waves-effect"><i class="fa fa-newspaper-o"></i> <span> مدیریت دسته بندی ها </span> </a>
                </li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-view-list"></i> <span> مدیریت محتوا </span> <span class="menu-arrow"></span></a>
                    <ul class="list-unstyled">
                        <li>
                            <a asp-area="Admin" asp-controller="AboutMe" asp-action="Index" class="waves-effect"><i class="fa fa-wordpress"></i> <span> درباره من </span> </a>
                        </li>

                        <li>
                            <a asp-area="Admin" asp-controller="Skills" asp-action="Index" class="waves-effect"><i class="fa fa-code"></i> <span> مهارت های من </span> </a>
                        </li>

                        <li>
                            <a asp-area="Admin" asp-controller="Portfolio" asp-action="Index" class="waves-effect"><i class="fa fa-exchange"></i> <span> نمونه کارهای من </span> </a>
                        </li>
                    </ul>
                </li>
                
                <li>
                    <a asp-area="Admin" asp-controller="Message" asp-action="Index" class="waves-effect"><i class="fa fa-envelope"></i> <span> بازخوردها </span> </a>
                </li>

                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="waves-effect"><i class="fa fa-arrow-right"></i> <span> بازگشت به صفحه اصلی </span> </a>
                </li>

            </ul>
            <div class="clearfix"></div>
        </div>
        <!-- Sidebar -->
        <div class="clearfix"></div>
    </div>
</div>